export enum HeroesEnum {
	ALCHEMIST = "Alchemist",
	AXE = "Axe",
	BRISTLEBACK = "Bristleback",
	CENTAUR_WARRUNNER = "Centaur Warrunner",
	CHAOS_KNIGHT = "Chaos Knight",
	DAWNBREAKER = "Dawnbreaker",
	DOOM = "Doom",
	DRAGON_KNIGHT = "Dragon Knight",
	EARTH_SPIRIT = "Earth Spirit",
	EARTHSHAKER = "Earthshaker",
	ELDER_TITAN = "Elder Titan",
	HUSKAR = "Huskar",
	KUNKKA = "Kunkka",
	LEGION_COMMANDER = "Legion Commander",
	LIFESTEALER = "Lifestealer",
	MARS = "Mars",
	NIGHT_STALKER = "Night Stalker",
	OGRE_MAGI = "Ogre Magi",
	OMNIKNIGHT = "Omniknight",
	PRIMAL_BEAST = "Primal Beast",
	PUDGE = "Pudge",
	SLARDAR = "Slardar",
	SPIRIT_BREAKER = "Spirit Breaker",
	SVEN = "Sven",
	TIDEHUNTER = "Tidehunter",
	TINY = "Tiny",
	TREANT_PROTECTOR = "Treant Protector",
	TUSK = "Tusk",
	UNDERLORD = "Underlord",
	UNDYING = "Undying",
	WRAITH_KING = "Wraith King",
	ANTI_MAGE = "Anti-Mage",
	ARC_WARDEN = "Arc Warden",
	BLOODSEEKER = "Bloodseeker",
	BOUNTY_HUNTER = "Bounty Hunter",
	CLINKZ = "Clinkz",
	DROW_RANGER = "Drow Ranger",
	EMBER_SPIRIT = "Ember Spirit",
	FACELESS_VOID = "Faceless Void",
	GYROCOPTER = "Gyrocopter",
	HOODWINK = "Hoodwink",
	JUGGERNAUT = "Juggernaut",
	LUNA = "Luna",
	MEDUSA = "Medusa",
	MEEPO = "Meepo",
	MONKEY_KING = "Monkey King",
	MORPHLING = "Morphling",
	NAGA_SIREN = "Naga Siren",
	PHANTOM_Assassin = "Phantom Assassin",
	PHANTOM_LANCER = "Phantom Lancer",
	RAZOR = "Razor",
	RIKI = "Riki",
	SHADOW_FIEND = "Shadow Fiend",
	SLARK = "Slark",
	SNIPER = "Sniper",
	SPECTRE = "Spectre",
	TEMPLAR_ASSASSIN = "Templar Assassin",
	TERRORBLADE = "Terrorblade",
	TROLL_WARLORD = "Troll Warlord",
	URSA = "Ursa",
	VIPER = "Viper",
	WEAVER = "Weaver",
	ANCIENT_APPARITION = "Ancient Apparition",
	CRYSTAL_MAIDEN = "Crystal Maiden",
	DEATH_PROPHET = "Death Prophet",
	DISRUPTOR = "Disruptor",
	ENCHANTRESS = "Enchantress",
	GRIMSTROKE = "Grimstroke",
	JAKIRO = "Jakiro",
	KEEPER_OF_THE_LIGHT = "Keeper of the Light",
	LESHRAC = "Leshrac",
	LICH = "Lich",
	LINA = "Lina",
	LION = "Lion",
	MUERTA = "Muerta",
	NATURE_S_PROPHET = "Nature's Prophet",
	NECROPHOS = "Necrophos",
	ORACLE = "Oracle",
	OUTWORLD_DESTROYER = "Outworld Destroyer",
	PUCK = "Puck",
	PUGNA = "Pugna",
	QUEEN_OF_PAIN = "Queen of Pain",
	RINGMASTER = "Ringmaster",
	RUBICK = "Rubick",
	SHADOW_DEMON = "Shadow Demon",
	SHADOW_SHAMAN = "Shadow Shaman",
	SILENCER = "Silencer",
	SKYWRATH_MAGE = "Skywrath Mage",
	STORM_SPIRIT = "Storm Spirit",
	TINKER = "Tinker",
	WARLOCK = "Warlock",
	WITCH_DOCTOR = "Witch Doctor",
	ZEUS = "Zeus",
	ABADDON = "Abaddon",
	BANE = "Bane",
	BATRIDER = "Batrider",
	BEASTMASTER = "Beastmaster",
	BREWMASTER = "Brewmaster",
	BROODMOTHER = "Broodmother",
	CHEN = "Chen",
	CLOCKWERK = "Clockwerk",
	DARK_SEER = "Dark Seer",
	DARK_WILLOW = "Dark Willow",
	DAZZLE = "Dazzle",
	ENIGMA = "Enigma",
	INVOKER = "Invoker",
	IO = "Io",
	LONE_DRUID = "Lone Druid",
	LYCAN = "Lycan",
	MAGNUS = "Magnus",
	MARCI = "Marci",
	MIRANA = "Mirana",
	NYX_ASSASSIN = "Nyx Assassin",
	PANGOLIER = "Pangolier",
	PHOENIX = "Phoenix",
	SAND_KING = "Sand King",
	SNAPFIRE = "Snapfire",
	TECHIES = "Techies",
	TIMBERSAW = "Timbersaw",
	VENGEFUL_SPIRIT = "Vengeful Spirit",
	VENOMANCER = "Venomancer",
	VISAGE = "Visage",
	VOID_SPIRIT = "Void Spirit",
	WINDRANGER = "Windranger",
	WINTER_WYVERN = "Winter Wyvern",
}

export const HEROES = [
	HeroesEnum.ALCHEMIST,
	HeroesEnum.AXE,
	HeroesEnum.BRISTLEBACK,
	HeroesEnum.CENTAUR_WARRUNNER,
	HeroesEnum.CHAOS_KNIGHT,
	HeroesEnum.DAWNBREAKER,
	HeroesEnum.DOOM,
	HeroesEnum.DRAGON_KNIGHT,
	HeroesEnum.EARTH_SPIRIT,
	HeroesEnum.EARTHSHAKER,
	HeroesEnum.ELDER_TITAN,
	HeroesEnum.HUSKAR,
	HeroesEnum.KUNKKA,
	HeroesEnum.LEGION_COMMANDER,
	HeroesEnum.LIFESTEALER,
	HeroesEnum.MARS,
	HeroesEnum.NIGHT_STALKER,
	HeroesEnum.OGRE_MAGI,
	HeroesEnum.OMNIKNIGHT,
	HeroesEnum.PRIMAL_BEAST,
	HeroesEnum.PUDGE,
	HeroesEnum.SLARDAR,
	HeroesEnum.SPIRIT_BREAKER,
	HeroesEnum.SVEN,
	HeroesEnum.TIDEHUNTER,
	HeroesEnum.TINY,
	HeroesEnum.TREANT_PROTECTOR,
	HeroesEnum.TUSK,
	HeroesEnum.UNDERLORD,
	HeroesEnum.UNDYING,
	HeroesEnum.WRAITH_KING,
	HeroesEnum.ANTI_MAGE,
	HeroesEnum.ARC_WARDEN,
	HeroesEnum.BLOODSEEKER,
	HeroesEnum.BOUNTY_HUNTER,
	HeroesEnum.CLINKZ,
	HeroesEnum.DROW_RANGER,
	HeroesEnum.EMBER_SPIRIT,
	HeroesEnum.FACELESS_VOID,
	HeroesEnum.GYROCOPTER,
	HeroesEnum.HOODWINK,
	HeroesEnum.JUGGERNAUT,
	HeroesEnum.LUNA,
	HeroesEnum.MEDUSA,
	HeroesEnum.MEEPO,
	HeroesEnum.MONKEY_KING,
	HeroesEnum.MORPHLING,
	HeroesEnum.NAGA_SIREN,
	HeroesEnum.PHANTOM_Assassin,
	HeroesEnum.PHANTOM_LANCER,
	HeroesEnum.RAZOR,
	HeroesEnum.RIKI,
	HeroesEnum.SHADOW_FIEND,
	HeroesEnum.SLARK,
	HeroesEnum.SNIPER,
	HeroesEnum.SPECTRE,
	HeroesEnum.TEMPLAR_ASSASSIN,
	HeroesEnum.TERRORBLADE,
	HeroesEnum.TROLL_WARLORD,
	HeroesEnum.URSA,
	HeroesEnum.VIPER,
	HeroesEnum.WEAVER,
	HeroesEnum.ANCIENT_APPARITION,
	HeroesEnum.CRYSTAL_MAIDEN,
	HeroesEnum.DEATH_PROPHET,
	HeroesEnum.DISRUPTOR,
	HeroesEnum.ENCHANTRESS,
	HeroesEnum.GRIMSTROKE,
	HeroesEnum.JAKIRO,
	HeroesEnum.KEEPER_OF_THE_LIGHT,
	HeroesEnum.LESHRAC,
	HeroesEnum.LICH,
	HeroesEnum.LINA,
	HeroesEnum.LION,
	HeroesEnum.MUERTA,
	HeroesEnum.NATURE_S_PROPHET,
	HeroesEnum.NECROPHOS,
	HeroesEnum.ORACLE,
	HeroesEnum.OUTWORLD_DESTROYER,
	HeroesEnum.PUCK,
	HeroesEnum.PUGNA,
	HeroesEnum.QUEEN_OF_PAIN,
	HeroesEnum.RINGMASTER,
	HeroesEnum.RUBICK,
	HeroesEnum.SHADOW_DEMON,
	HeroesEnum.SHADOW_SHAMAN,
	HeroesEnum.SILENCER,
	HeroesEnum.SKYWRATH_MAGE,
	HeroesEnum.STORM_SPIRIT,
	HeroesEnum.TINKER,
	HeroesEnum.WARLOCK,
	HeroesEnum.WITCH_DOCTOR,
	HeroesEnum.ZEUS,
	HeroesEnum.ABADDON,
	HeroesEnum.BANE,
	HeroesEnum.BATRIDER,
	HeroesEnum.BEASTMASTER,
	HeroesEnum.BREWMASTER,
	HeroesEnum.BROODMOTHER,
	HeroesEnum.CHEN,
	HeroesEnum.CLOCKWERK,
	HeroesEnum.DARK_SEER,
	HeroesEnum.DARK_WILLOW,
	HeroesEnum.DAZZLE,
	HeroesEnum.ENIGMA,
	HeroesEnum.INVOKER,
	HeroesEnum.IO,
	HeroesEnum.LONE_DRUID,
	HeroesEnum.LYCAN,
	HeroesEnum.MAGNUS,
	HeroesEnum.MARCI,
	HeroesEnum.MIRANA,
	HeroesEnum.NYX_ASSASSIN,
	HeroesEnum.PANGOLIER,
	HeroesEnum.PHOENIX,
	HeroesEnum.SAND_KING,
	HeroesEnum.SNAPFIRE,
	HeroesEnum.TECHIES,
	HeroesEnum.TIMBERSAW,
	HeroesEnum.VENGEFUL_SPIRIT,
	HeroesEnum.VENOMANCER,
	HeroesEnum.VISAGE,
	HeroesEnum.VOID_SPIRIT,
	HeroesEnum.WINDRANGER,
	HeroesEnum.WINTER_WYVERN,
];
