export enum ConsumablesEnum {
	OBSERVER_WARD = "Observer Ward",
	BLOOD_GRENADE = "Blood Grenade",
	CLARITY = "Clarity",
	SENTRY_WARD = "Sentry Ward",
	SMOKE_OF_DECEIT = "Smoke of Deceit",
	ENCHANTED_MANGO = "Enchanted Mango",
	FAERIE_FIRE = "Faerie Fire",
	DUST_OF_APPEARANCE = "Dust of Appearance",
	TANGO = "Tango",
	HEALING_SALVE = "Healing Salve",
	TOWN_PORTAL_SCROLL = "Town Portal Scroll",
	BOTTLE = "Bottle",
}
//
// export const CONSUMABLES = [
// 	ConsumablesEnum.OBSERVER_WARD,
// 	ConsumablesEnum.BLOOD_GRENADE,
// 	ConsumablesEnum.CLARITY,
// 	ConsumablesEnum.SENTRY_WARD,
// 	ConsumablesEnum.SMOKE_OF_DECEIT,
// 	ConsumablesEnum.ENCHANTED_MANGO,
// 	ConsumablesEnum.FAERIE_FIRE,
// 	ConsumablesEnum.DUST_OF_APPEARANCE,
// 	ConsumablesEnum.TANGO,
// 	ConsumablesEnum.HEALING_SALVE,
// 	ConsumablesEnum.TOWN_PORTAL_SCROLL,
// 	ConsumablesEnum.BOTTLE,
// ];

// Aghanim's Shard (1400) Aghanim's Shard (1400 Gold)

export enum AccessoriesEnum {
	MAGIC_WAND = "Magic Wand",
	BRACER = "Bracer",
	NULL_TALISMAN = "Null Talisman",
	WRAITH_BAND = "Wraith Band",
	SOUL_RING = "Soul Ring",
	ORB_OF_CORROSION = "Orb of Corrosion",
	FALCON_BLADE = "Falcon Blade",
	PERSEVERANCE = "Perseverance",
	POWER_TREADS = "Power Treads",
	PHASE_BOOTS = "Phase Boots",
	OBLIVION_STAFF = "Oblivion Staff",
	MASK_OF_MADNESS = "Mask of Madness",
	HAND_OF_MIDAS = "Hand of Midas",
	BOOTS_OF_TRAVEL = "Boots of Travel",
	HELM_OF_THE_DOMINATOR = "Helm of the Dominator",
	MOON_SHARD = "Moon Shard",
	HELM_OF_THE_OVERLORD = "Helm of the Overlord",
}

export enum SupportEnum {
	BUCKLER = "Buckler",
	HEADDRESS = "Headdress",
	RING_OF_BASILIUS = "Ring of Basilius",
	URN_OF_SHADOWS = "Urn of Shadows",
	TRANQUIL_BOOTS = "Tranquil Boots",
	ARCANE_BOOTS = "Arcane Boots",
	PAVISE = "Pavise",
	DRUM_OF_ENDURANCE = "Drum of Endurance",
	MEKANSM = "Mekansm",
	VLADMIRS_OFFERING = "Vladmir's Offering",
	HOLY_LOCKET = "Holy Locket",
	SPIRIT_VESSEL = "Spirit Vessel",
	PIPE_OF_INSIGHT = "Pipe of Insight",
	BOOTS_OF_BEARING = "Boots of Bearing",
	GUARDIAN_GREAVES = "Guardian Greaves",
	PARASMA = "Parasma",
}

export enum MagicalEnum {
	VEIL_OF_DISCORD = "Veil of Discord",
	GLIMMER_CAPE = "Glimmer Cape",
	FORCE_STAFF = "Force Staff",
	ROD_OF_ATOS = "Rod of Atos",
	AETHER_LENS = "Aether Lens",
	EULS_SCEPTER_OF_DIVINITY = "Eul's Scepter of Divinity",
	SOLAR_CREST = "Solar Crest",
	WITCH_BLADE = "Witch Blade",
	DAGON = "Dagon",
	ORCHID_MALEVOLENCE = "Orchid Malevolence",
	AGHANIMS_SCEPTER = "Aghanim's Scepter",
	OCTARINE_CORE = "Octarine Core",
	REFRESHER_ORB = "Refresher Orb",
	SCYTHE_OF_VYSE = "Scythe of Vyse",
	GLEIPNIR = "Gleipnir",
	AGHANIMS_BLESSING = "Aghanim's Blessing",
	WIND_WAKER = "Wind Waker",
}

export enum ArmorEnum {
	VANGUARD = "Vanguard",
	BLADE_MAIL = "Blade Mail",
	AEON_DISK = "Aeon Disk",
	SOUL_BOOSTER = "Soul Booster",
	ETERNAL_SHROUD = "Eternal Shroud",
	CRIMSON_GUARD = "Crimson Guard",
	LOTUS_ORB = "Lotus Orb",
	BLACK_KING_BAR = "Black King Bar",
	BLOODSTONE = "Bloodstone",
	HURRICANE_PIKE = "Hurricane Pike",
	MANTA_STYLE = "Manta Style",
	LINKENS_SPHERE = "Linken's Sphere",
	ASSAULT_CUIRASS = "Assault Cuirass",
	SHIVAS_GUARD = "Shiva's Guard",
	HEART_OF_TARRASQUE = "Heart of Tarrasque",
}

export enum WeaponsEnum {
	CRYSTALYS = "Crystalys",
	ARMLET_OF_MORDIGGIAN = "Armlet of Mordiggian",
	METEOR_HAMMER = "Meteor Hammer",
	SKULL_BASHER = "Skull Basher",
	SHADOW_BLADE = "Shadow Blade",
	DESOLATOR = "Desolator",
	BATTLE_FURY = "Battle Fury",
	NULLIFIER = "Nullifier",
	MONKEY_KING_BAR = "Monkey King Bar",
	RADIANCE = "Radiance",
	REVENANTS_BROOCH = "Revenant's Brooch",
	KHANDA = "Khanda",
	DAEDALUS = "Daedalus",
	ETHEREAL_BLADE = "Ethereal Blade",
	BUTTERFLY = "Butterfly",
	SILVER_EDGE = "Silver Edge",
	ABYSSAL_BLADE = "Abyssal Blade",
	DIVINE_RAPIER = "Divine Rapier",
	DISPERSER = "Disperser",
	BLOODTHORN = "Bloodthorn",
}

export enum ArtifactsEnum {
	DRAGON_LANCE = "Dragon Lance",
	KAYA = "Kaya",
	SANGE = "Sange",
	YASHA = "Yasha",
	PHYLACTERY = "Phylactery",
	DIFFUSAL_BLADE = "Diffusal Blade",
	ECHO_SABRE = "Echo Sabre",
	MAGE_SLAYER = "Mage Slayer",
	MAELSTROM = "Maelstrom",
	HEAVENS_HALBERD = "Heaven's Halberd",
	YASHA_AND_KAYA = "Yasha and Kaya",
	KAYA_AND_SANGE = "Kaya and Sange",
	SANGE_AND_YASHA = "Sange and Yasha",
	HARPOON = "Harpoon",
	SATANIC = "Satanic",
	EYE_OF_SKADI = "Eye of Skadi",
	MJOLLNIR = "Mjollnir",
	ARCANE_BLINK = "Arcane Blink",
	OVERWHELMING_BLINK = "Overwhelming Blink",
	SWIFT_BLINK = "Swift Blink",
}

export const ItemsSections = {
	CONSUMABLES: ConsumablesEnum,
	ACCESSORIES: AccessoriesEnum,
	SUPPORT: SupportEnum,
	MAGICAL: MagicalEnum,
	ARMOR: ArmorEnum,
	WEAPONS: WeaponsEnum,
	ARTIFACTS: ArtifactsEnum,
};

export const BootsSection = {
	PURE_BOOTS: "Pure Boots",
	PHASE_BOOTS: AccessoriesEnum.PHASE_BOOTS,
	POWER_TREADS: AccessoriesEnum.POWER_TREADS,
	TRANQUIL_BOOTS: SupportEnum.TRANQUIL_BOOTS,
	ARCANE_BOOTS: SupportEnum.ARCANE_BOOTS,
	BOOTS_OF_TRAVEL: AccessoriesEnum.BOOTS_OF_TRAVEL,
};
