export enum ItemsEnum {
	OBSERVER_WARD = "Observer Ward",
	BLOOD_GRENADE = "Blood Grenade",
	CLARITY = "Clarity",
	SENTRY_WARD = "Sentry Ward",
	SMOKE_OF_DECEIT = "Smoke of Deceit",
	ENCHANTED_MANGO = "Enchanted Mango",
	FAERIE_FIRE = "Faerie Fire",
	DUST_OF_APPEARANCE = "Dust of Appearance",
	TANGO = "Tango",
	HEALING_SALVE = "Healing Salve",
	TOWN_PORTAL_SCROLL = "Town Portal Scroll",
	BOTTLE = "Bottle",
	BOOTS_OF_SPEED = "Boots Of Speed",
	MAGIC_WAND = "Magic Wand",
	BRACER = "Bracer",
	NULL_TALISMAN = "Null Talisman",
	WRAITH_BAND = "Wraith Band",
	SOUL_RING = "Soul Ring",
	ORB_OF_CORROSION = "Orb of Corrosion",
	FALCON_BLADE = "Falcon Blade",
	PERSEVERANCE = "Perseverance",
	POWER_TREADS = "Power Treads",
	PHASE_BOOTS = "Phase Boots",
	OBLIVION_STAFF = "Oblivion Staff",
	MASK_OF_MADNESS = "Mask of Madness",
	HAND_OF_MIDAS = "Hand of Midas",
	BOOTS_OF_TRAVEL = "Boots of Travel",
	HELM_OF_THE_DOMINATOR = "Helm of the Dominator",
	MOON_SHARD = "Moon Shard",
	HELM_OF_THE_OVERLORD = "Helm of the Overlord",
	BUCKLER = "Buckler",
	HEADDRESS = "Headdress",
	RING_OF_BASILIUS = "Ring of Basilius",
	URN_OF_SHADOWS = "Urn of Shadows",
	TRANQUIL_BOOTS = "Tranquil Boots",
	ARCANE_BOOTS = "Arcane Boots",
	PAVISE = "Pavise",
	DRUM_OF_ENDURANCE = "Drum of Endurance",
	MEKANSM = "Mekansm",
	VLADMIRS_OFFERING = "Vladmir's Offering",
	HOLY_LOCKET = "Holy Locket",
	SPIRIT_VESSEL = "Spirit Vessel",
	PIPE_OF_INSIGHT = "Pipe of Insight",
	BOOTS_OF_BEARING = "Boots of Bearing",
	GUARDIAN_GREAVES = "Guardian Greaves",
	PARASMA = "Parasma",
	VEIL_OF_DISCORD = "Veil of Discord",
	GLIMMER_CAPE = "Glimmer Cape",
	FORCE_STAFF = "Force Staff",
	ROD_OF_ATOS = "Rod of Atos",
	AETHER_LENS = "Aether Lens",
	EULS_SCEPTER_OF_DIVINITY = "Eul's Scepter of Divinity",
	SOLAR_CREST = "Solar Crest",
	WITCH_BLADE = "Witch Blade",
	DAGON = "Dagon",
	ORCHID_MALEVOLENCE = "Orchid Malevolence",
	AGHANIMS_SCEPTER = "Aghanim's Scepter",
	OCTARINE_CORE = "Octarine Core",
	REFRESHER_ORB = "Refresher Orb",
	SCYTHE_OF_VYSE = "Scythe of Vyse",
	GLEIPNIR = "Gleipnir",
	AGHANIMS_BLESSING = "Aghanim's Blessing",
	WIND_WAKER = "Wind Waker",
	VANGUARD = "Vanguard",
	BLADE_MAIL = "Blade Mail",
	AEON_DISK = "Aeon Disk",
	SOUL_BOOSTER = "Soul Booster",
	ETERNAL_SHROUD = "Eternal Shroud",
	CRIMSON_GUARD = "Crimson Guard",
	LOTUS_ORB = "Lotus Orb",
	BLACK_KING_BAR = "Black King Bar",
	BLOODSTONE = "Bloodstone",
	HURRICANE_PIKE = "Hurricane Pike",
	MANTA_STYLE = "Manta Style",
	LINKENS_SPHERE = "Linken's Sphere",
	ASSAULT_CUIRASS = "Assault Cuirass",
	SHIVAS_GUARD = "Shiva's Guard",
	HEART_OF_TARRASQUE = "Heart of Tarrasque",
	CRYSTALYS = "Crystalys",
	ARMLET_OF_MORDIGGIAN = "Armlet of Mordiggian",
	METEOR_HAMMER = "Meteor Hammer",
	SKULL_BASHER = "Skull Basher",
	SHADOW_BLADE = "Shadow Blade",
	DESOLATOR = "Desolator",
	BATTLE_FURY = "Battle Fury",
	NULLIFIER = "Nullifier",
	MONKEY_KING_BAR = "Monkey King Bar",
	RADIANCE = "Radiance",
	REVENANTS_BROOCH = "Revenant's Brooch",
	KHANDA = "Khanda",
	DAEDALUS = "Daedalus",
	ETHEREAL_BLADE = "Ethereal Blade",
	BUTTERFLY = "Butterfly",
	SILVER_EDGE = "Silver Edge",
	ABYSSAL_BLADE = "Abyssal Blade",
	DIVINE_RAPIER = "Divine Rapier",
	DISPERSER = "Disperser",
	BLOODTHORN = "Bloodthorn",
	DRAGON_LANCE = "Dragon Lance",
	KAYA = "Kaya",
	SANGE = "Sange",
	YASHA = "Yasha",
	PHYLACTERY = "Phylactery",
	DIFFUSAL_BLADE = "Diffusal Blade",
	ECHO_SABRE = "Echo Sabre",
	MAGE_SLAYER = "Mage Slayer",
	MAELSTROM = "Maelstrom",
	HEAVENS_HALBERD = "Heaven's Halberd",
	YASHA_AND_KAYA = "Yasha and Kaya",
	KAYA_AND_SANGE = "Kaya and Sange",
	SANGE_AND_YASHA = "Sange and Yasha",
	HARPOON = "Harpoon",
	SATANIC = "Satanic",
	EYE_OF_SKADI = "Eye of Skadi",
	MJOLLNIR = "Mjollnir",
	ARCANE_BLINK = "Arcane Blink",
	OVERWHELMING_BLINK = "Overwhelming Blink",
	SWIFT_BLINK = "Swift Blink",
}

export const ConsumablesSection = [
	ItemsEnum.OBSERVER_WARD,
	ItemsEnum.BLOOD_GRENADE,
	ItemsEnum.CLARITY,
	ItemsEnum.SENTRY_WARD,
	ItemsEnum.SMOKE_OF_DECEIT,
	ItemsEnum.ENCHANTED_MANGO,
	ItemsEnum.FAERIE_FIRE,
	ItemsEnum.DUST_OF_APPEARANCE,
	ItemsEnum.TANGO,
	ItemsEnum.HEALING_SALVE,
	ItemsEnum.TOWN_PORTAL_SCROLL,
	ItemsEnum.BOTTLE,
];

// Aghanim's Shard (1400) Aghanim's Shard (1400 Gold)

export const AccessoriesSection = [
	ItemsEnum.MAGIC_WAND,
	ItemsEnum.BRACER,
	ItemsEnum.NULL_TALISMAN,
	ItemsEnum.WRAITH_BAND,
	ItemsEnum.SOUL_RING,
	ItemsEnum.ORB_OF_CORROSION,
	ItemsEnum.FALCON_BLADE,
	ItemsEnum.PERSEVERANCE,
	ItemsEnum.POWER_TREADS,
	ItemsEnum.PHASE_BOOTS,
	ItemsEnum.OBLIVION_STAFF,
	ItemsEnum.MASK_OF_MADNESS,
	ItemsEnum.HAND_OF_MIDAS,
	ItemsEnum.BOOTS_OF_TRAVEL,
	ItemsEnum.HELM_OF_THE_DOMINATOR,
	ItemsEnum.MOON_SHARD,
	ItemsEnum.HELM_OF_THE_OVERLORD,
];

export const SupportSection = [
	ItemsEnum.BUCKLER,
	ItemsEnum.HEADDRESS,
	ItemsEnum.RING_OF_BASILIUS,
	ItemsEnum.URN_OF_SHADOWS,
	ItemsEnum.TRANQUIL_BOOTS,
	ItemsEnum.ARCANE_BOOTS,
	ItemsEnum.PAVISE,
	ItemsEnum.DRUM_OF_ENDURANCE,
	ItemsEnum.MEKANSM,
	ItemsEnum.VLADMIRS_OFFERING,
	ItemsEnum.HOLY_LOCKET,
	ItemsEnum.SPIRIT_VESSEL,
	ItemsEnum.PIPE_OF_INSIGHT,
	ItemsEnum.BOOTS_OF_BEARING,
	ItemsEnum.GUARDIAN_GREAVES,
	ItemsEnum.PARASMA,
];

export const MagicalSection = [
	ItemsEnum.VEIL_OF_DISCORD,
	ItemsEnum.GLIMMER_CAPE,
	ItemsEnum.FORCE_STAFF,
	ItemsEnum.ROD_OF_ATOS,
	ItemsEnum.AETHER_LENS,
	ItemsEnum.EULS_SCEPTER_OF_DIVINITY,
	ItemsEnum.SOLAR_CREST,
	ItemsEnum.WITCH_BLADE,
	ItemsEnum.DAGON,
	ItemsEnum.ORCHID_MALEVOLENCE,
	ItemsEnum.AGHANIMS_SCEPTER,
	ItemsEnum.OCTARINE_CORE,
	ItemsEnum.REFRESHER_ORB,
	ItemsEnum.SCYTHE_OF_VYSE,
	ItemsEnum.GLEIPNIR,
	ItemsEnum.AGHANIMS_BLESSING,
	ItemsEnum.WIND_WAKER,
];

export const ArmorSection = [
	ItemsEnum.VANGUARD,
	ItemsEnum.BLADE_MAIL,
	ItemsEnum.AEON_DISK,
	ItemsEnum.SOUL_BOOSTER,
	ItemsEnum.ETERNAL_SHROUD,
	ItemsEnum.CRIMSON_GUARD,
	ItemsEnum.LOTUS_ORB,
	ItemsEnum.BLACK_KING_BAR,
	ItemsEnum.BLOODSTONE,
	ItemsEnum.HURRICANE_PIKE,
	ItemsEnum.MANTA_STYLE,
	ItemsEnum.LINKENS_SPHERE,
	ItemsEnum.ASSAULT_CUIRASS,
	ItemsEnum.SHIVAS_GUARD,
	ItemsEnum.HEART_OF_TARRASQUE,
];

export const WeaponsSection = [
	ItemsEnum.CRYSTALYS,
	ItemsEnum.ARMLET_OF_MORDIGGIAN,
	ItemsEnum.METEOR_HAMMER,
	ItemsEnum.SKULL_BASHER,
	ItemsEnum.SHADOW_BLADE,
	ItemsEnum.DESOLATOR,
	ItemsEnum.BATTLE_FURY,
	ItemsEnum.NULLIFIER,
	ItemsEnum.MONKEY_KING_BAR,
	ItemsEnum.RADIANCE,
	ItemsEnum.REVENANTS_BROOCH,
	ItemsEnum.KHANDA,
	ItemsEnum.DAEDALUS,
	ItemsEnum.ETHEREAL_BLADE,
	ItemsEnum.BUTTERFLY,
	ItemsEnum.SILVER_EDGE,
	ItemsEnum.ABYSSAL_BLADE,
	ItemsEnum.DIVINE_RAPIER,
	ItemsEnum.DISPERSER,
	ItemsEnum.BLOODTHORN,
];

export const ArtifactsSection = [
	ItemsEnum.DRAGON_LANCE,
	ItemsEnum.KAYA,
	ItemsEnum.SANGE,
	ItemsEnum.YASHA,
	ItemsEnum.PHYLACTERY,
	ItemsEnum.DIFFUSAL_BLADE,
	ItemsEnum.ECHO_SABRE,
	ItemsEnum.MAGE_SLAYER,
	ItemsEnum.MAELSTROM,
	ItemsEnum.HEAVENS_HALBERD,
	ItemsEnum.YASHA_AND_KAYA,
	ItemsEnum.KAYA_AND_SANGE,
	ItemsEnum.SANGE_AND_YASHA,
	ItemsEnum.HARPOON,
	ItemsEnum.SATANIC,
	ItemsEnum.EYE_OF_SKADI,
	ItemsEnum.MJOLLNIR,
	ItemsEnum.ARCANE_BLINK,
	ItemsEnum.OVERWHELMING_BLINK,
	ItemsEnum.SWIFT_BLINK,
];

export const ItemsSections = [
	SupportSection,
	MagicalSection,
	ArmorSection,
	WeaponsSection,
	ArtifactsSection,
];

export const BootsSection = [
	ItemsEnum.BOOTS_OF_SPEED,
	ItemsEnum.PHASE_BOOTS,
	ItemsEnum.POWER_TREADS,
	ItemsEnum.TRANQUIL_BOOTS,
	ItemsEnum.ARCANE_BOOTS,
	ItemsEnum.BOOTS_OF_TRAVEL,
];
